# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/root/bbec4a69-88a4-49a5-a0b2-ba370f035ffd/Yyzh-test/LSM-based-on-ZNS-SSD-remove_pqueue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/root/bbec4a69-88a4-49a5-a0b2-ba370f035ffd/Yyzh-test/LSM-based-on-ZNS-SSD-remove_pqueue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/root/bbec4a69-88a4-49a5-a0b2-ba370f035ffd/Yyzh-test/LSM-based-on-ZNS-SSD-remove_pqueue/CMakeFiles /run/media/root/bbec4a69-88a4-49a5-a0b2-ba370f035ffd/Yyzh-test/LSM-based-on-ZNS-SSD-remove_pqueue//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/root/bbec4a69-88a4-49a5-a0b2-ba370f035ffd/Yyzh-test/LSM-based-on-ZNS-SSD-remove_pqueue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ZNS-SSD

# Build rule for target.
ZNS-SSD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ZNS-SSD
.PHONY : ZNS-SSD

# fast build rule for target.
ZNS-SSD/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ZNS-SSD.dir/build.make src/CMakeFiles/ZNS-SSD.dir/build
.PHONY : ZNS-SSD/fast

#=============================================================================
# Target rules for targets named femu

# Build rule for target.
femu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 femu
.PHONY : femu

# fast build rule for target.
femu/fast:
	$(MAKE) $(MAKESILENT) -f src/femu/CMakeFiles/femu.dir/build.make src/femu/CMakeFiles/femu.dir/build
.PHONY : femu/fast

#=============================================================================
# Target rules for targets named LSM-Tree

# Build rule for target.
LSM-Tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LSM-Tree
.PHONY : LSM-Tree

# fast build rule for target.
LSM-Tree/fast:
	$(MAKE) $(MAKESILENT) -f src/LSM-Tree/CMakeFiles/LSM-Tree.dir/build.make src/LSM-Tree/CMakeFiles/LSM-Tree.dir/build
.PHONY : LSM-Tree/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LSM-Tree"
	@echo "... ZNS-SSD"
	@echo "... femu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

